export const SET_TEMPLATE_NAMES = "SET_TEMPLATE_NAMES";
export const SET_SELECTED_TEMPLATE_NAME = "SET_SELECTED_TEMPLATE_NAME";
export const SET_SELECTED_TEMPLATE_CONTEXT = "SET_SELECTED_TEMPLATE_CONTEXT";
export const SET_GLOBAL_ERROR = "SET_GLOBAL_ERROR";
export const CLEAR_GLOBAL_ERROR = "CLEAR_GLOBAL_ERROR";
export const SET_CONTEXT_VARIABLES = "SET_CONTEXT_VARIABLES";
export const SET_IS_LOADING = "SET_IS_LOADING";